name: Build U-Boot with Splash and Fastboot

on:
  push:
  workflow_dispatch:

jobs:
  build-uboot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc-aarch64-linux-gnu bison flex \
          libssl-dev device-tree-compiler python3-pyelftools wget

    - name: Clone U-Boot
      run: |
        git clone https://github.com/u-boot/u-boot.git --depth=1
        cd u-boot

        # Dùng cấu hình QEMU ARM64
        make CROSS_COMPILE=aarch64-linux-gnu- qemu_arm64_defconfig

        # Bật splash
        echo "CONFIG_SPLASH_SCREEN=y" >> .config
        echo "CONFIG_VIDEO=y" >> .config
        echo "CONFIG_VIDEO_LOGO=y" >> .config

        # Bật fastboot USB
        echo "CONFIG_CMD_FASTBOOT=y" >> .config
        echo "CONFIG_USB_FUNCTION_FASTBOOT=y" >> .config
        echo "CONFIG_USB_GADGET=y" >> .config
        echo "CONFIG_USB_GADGET_MANUFACTURER=\"FakePhone Inc\"" >> .config
        echo "CONFIG_FASTBOOT_FLASH=y" >> .config

        # Tắt mkeficapsule để tránh lỗi gnutls
        echo "CONFIG_TOOLS_MKEFICAPSULE=n" >> .config

        # Cập nhật config
        make olddefconfig

    - name: Build U-Boot
      run: |
        cd u-boot
        make -j$(nproc) CROSS_COMPILE=aarch64-linux-gnu-

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: u-boot-output
        path: |
          u-boot/u-boot.bin
          u-boot/u-boot.img
          u-boot/System.map
