name: Build U-Boot QEMU ARM64 (Splash mặc định)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-uboot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          gcc-aarch64-linux-gnu make bison flex libssl-dev

    - name: Clone U-Boot from GitHub mirror
      run: |
        git clone --depth=1 https://github.com/u-boot/u-boot.git
        cd u-boot

        # Dùng config cho QEMU ARM64
        make qemu_arm64_defconfig

        # Bật splash screen mặc định (không dùng ảnh ngoài)
        echo "CONFIG_VIDEO=y" >> .config
        echo "CONFIG_DM_VIDEO=y" >> .config
        echo "CONFIG_VIDEO_LOGO=y" >> .config
        echo "CONFIG_SYS_WHITE_ON_BLACK=y" >> .config
        echo "CONFIG_SPLASH_SCREEN=y" >> .config

        make olddefconfig

        # Build chính U-Boot, không build tool EFI để tránh lỗi
        make -j$(nproc) CROSS_COMPILE=aarch64-linux-gnu-

    - name: Save build output
      run: |
        mkdir -p output
        cp u-boot/u-boot.bin output/

    - name: Upload bootloader artifact
      uses: actions/upload-artifact@v4
      with:
        name: u-boot-splash-default
        path: output/
